# .goreleaser.yml
project_name: nocino
builds:
  - main: cli/main.go
    binary: nocino
    goos:
      - darwin
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
archives:
  - id: github
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    format: tar.gz
    files:
    - LICENSE*
    - README*      
dockers:
  - image_templates:
    - "frapposelli/nocino:latest"
    - "frapposelli/nocino:{{ .Tag }}"
    - "frapposelli/nocino:v{{ .Major }}"
    goos: linux
    goarch: amd64
    binaries:
    - nocino
    dockerfile: Dockerfile
