name: release

on:
  push:
    branches-ignore:
      - '**'
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Unshallow
        run: git fetch --prune --unshallow
      - 
        name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.14.x
      - 
        name: Registry login
        run: docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD} docker.io
        env:
          DOCKER_USERNAME: frapposelli
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v1
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
